name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Read Debug Keystore
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.config/.android/
        echo "$ANDROID_DEBUG_KEYSTORE" | base64 -d > ~/.config/.android/debug.keystore
      env:
        ANDROID_DEBUG_KEYSTORE: ${{ secrets.ANDROID_DEBUG_KEYSTORE }}
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: launcher-debug-${{ github.sha }}.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Delete Old Pre-Release
      if: github.ref == 'refs/heads/main'
      run: gh release delete pre-release --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pre-Release
      if: github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.sha }}
        tag: "pre-release"
        name: "Debug (only for testing)"
        prerelease: true
        body: "This debug build is updated automatically whenever there is a commit to main. It is signed with a debug certificate. **Debug builds are not suited for everyday use.**"
        generateReleaseNotes: true
        removeArtifacts: true
        replacesArtifacts: true
        artifacts: "app/build/outputs/apk/debug/app-debug.apk"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
